name: run

on:
  schedule:
    - '0 */2 * * *' # every 2 hours

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci --no-audit
      - run: npm run build
      - run: npm start
        env:
          FFX_TOKEN: ${{ secrets.FFX_TOKEN }}
