name: run

on:
  schedule:
    - cron: 0 */2 * * *
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci --no-audit
      - run: npm run build
      - run: npm start
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
